import './globals.css';

export const metadata = {
  title: 'ITube Assistir video',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" type="image/ " />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
