
// import './globals.css';
// import Head from 'next/head';

// export const metadata = {
//   title: 'ITube',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//       <link rel="icon" href="/favicon.ico" />
//     </html>
//   )
// }

import './globals.css';

export const metadata = {
  title: 'ITube',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
